[tool.ruff]
line-length = 120
indent-width = 4

[tool.ruff.lint]
# "I" is for imports, works as an alternative to isort
# The rest are defaults that ruff comes with as seen https://github.com/astral-sh/ruff?tab=readme-ov-file#configuration
select = ["I", "F", "E4", "E7", "E9"]

[tool.mypy]
ignore_missing_imports = true
exclude = ["env", "venv"]
